** Bayan Taksici

   *Gazeteci: Nevin Hanım, çok ilginç bir işiniz var Neden taksici oldunuz?*
   Невин Ханым, очень интересная ваша работа есть. Отчего таксистом стали вы?

   *Nevin Sağlam: Taksicilikten önce pek çok iş yaptım.*
   Водителя такси раньше, много много работ делала
   *En son küçük bir konfeksiyon mağazası açtım.*
   Самое последнее — маленький магазин сладостей я открыла
   *O zamanlar taksicilik hiç aklımda yoktu ama babam taksiciydi.*
   В то время, водителя такси вообще на уме моём не было, но мой отец таксистом был

   *Gazeteci: Peki bu mesleğe nasıl başladınız?*
   Окей, эту профессию как начали вы?

   *Nevin Sağlam: Mağazada işler kötüydü ve babam hastalandı.*
   В магазине дела плохи были и отец мой заболел.
   *Ben de babamın arabasıyla taksiciliğe başladım.*
   Я тоже отца моего машиной к таксисту начала

   *Gazeteci: Mesleğinizi seviyor musunuz?*
   Профессию вашу любите ли вы?

   *Nevin Sağlam: Her işin zorlukları var. Ben işmi seviyorum ve hep bu işi yapmak istiyorum*
   У каждой работы сложности есть. Я свою работу люблю и всегда эту работу делать хочу

   *Gazeteci: Peki müşteriliriniz nasıl tepkiler veriyor?*
   Окей, пассажиры ваши какую реакцию дают?

   *Nevin Sağlam: Hiç olumsuz bir tepki almadım ama genelikle biraz şaşırıyorlar.*
   Вообще отрицательную реакцию не получаю но обычно немного удивляются

   *Gazeteci: Peki ilginç olaylar yaşıyor musunuz?*
   Окей, любопытные ситуации переживаете?

   *Nevin Sağlam: Evet, geçen gün taksime bir çocuk bindi.*
   Да, прошедший день в моём такси ребёнок ехал
   *Yolda annesine telefon etmek için benden telefonumu istedi, ben de verdim.*
   На дороге своей маме телефон сделать чтобы моего телефона хотел, я же дала
   *O sırada kırmızı ışık yandı ve çocuk elinde telefonumla kaçtı*
   В это время красный свет загорелся и ребёнок в руке с телефоном моим сбежал

** Sayfa 47, Egzersiz 10

  Nevin Hanım kim?
  Nevin Sağlam bayan taksici

  Neden taksicilik yapıyor
  O taksicilikten önce çok iş yaptı, ama bir kere mağazasıda işler kötüleşti. İyi ki, onun babasını bir araba vardı.

  İşini seviyor mu?
  Even, işini çok seviyor.
  
** Rusya'da taksicilik nasıl yapılıyor?
1. За последние несколько лет такси в России очень изменилось
Son birkaç yılda, Rusya'daki taksi çok değişti.

2. Раньше можно было просто выйти на улицу и остановить любую машину.
Daha önce, sadece dışarı çıkıp rastgele bir arabayı durdurabilirdi.

3. Позже стали популярны фирмы, в которых вызывали такси по телефону, а машины координировались по радио.
Daha sonra, farklı yöntem popüler hale gelir. Biri telefonda taksi çağırır ve sürücüler radyo ile koordine edilir.

4. Всё ещё самые разные машины использовались как такси.
Yine de taksi olarak çok farklı arabalar kullanılıyordu.

5. Наконец, появился навигационный софт и агрегатов такси.
Son olarak, navigasyon yazılımı ve taksi koordinasyon yazılımı ortaya çıktı.

6. Кроме того, поменяли правила дорожного движения.
Ayrıca trafik düzenlemeleri değiştirildi.

7. Теперь такси стало дешевле.
Şimdi taksi daha ucuz hale geldi

8. Иногда поехать на такси быстрее, чем на собственной машине.
Bazen, taksiyle gitmek kendi aracınızdan daha hızlıdır.

9. Также есть и проблемы: комиссии агрегаторов довольно высокие.
Sorunlar da var: koordinatör komisyonu oldukça yüksek.

10. Самый большой агрегатор в России - Яндекс.
Rusya'daki en büyük taksi toplayıcısı Yandex'dir.

11. Сейчас они работают над созданием беспилотного автомобиля.
Şimdi sürücüsüz bir araba geliştiriyorlar.
** Normal bir günüm
1. Сейчас в Москве большинство людей работает из дома, поэтому нормальный распорядок дня изменился.
Şu anda, Moskova'daki insanlar evden çok çalışıyor, bu yüzden normal gün farklı görünüyor.

2. Я встаю около девяти часов.
Sabah 9 civarı uyanıyorum ve duş alırım ve  dişlerimi fırçalarım.

3. После этого, я пью чашку кофе с сигаретой.
Şundan sonra, ben bir fincan kahve ve sigara içerim.

4. В десять часов я бужу детей и помогаю им умываться
On yaşındayken çocuklarımı uyandırım ve onları yıkatırım.

Позже, я или жена для всей семьи готовим завтрак
5. Sonra, ben veya karım tün aile için kahvaltı yapar.

6. В одиннадцать, я начинаю работать и до двух часов работаю.
Onbiride, çalışmaya başlarım ve ikiye kadar çalışıyorum.

7. В два часа я или жена готовим обед и едим.
İki yaşında, ben ya da karım öğle yemeği hazırlıyoruz ve yiyoruz.

8. После обеда, если погода хорошая, то мы выходим на прогулку, если плохая то спим.
Öğle yemeği sonra, hava güzelse yürüyüşe çıkarız, hava kötü ise uyuruz.

9. В четыре часа я снова начинаю работать и работаю до семи.
Dördüncüsü, tekrar çalışmaya başlıyorum ve yediye kadar çalışıyorum.

10. После работы ещё раз мы идём на прогулку. Если нам нужна еда, то идём в магазин.
Çalışmadan sonra tekrar yürüyüşe çıkabiliriz. Yemeğe ihtiyacımız olursa dükkana gideriz.

11. В 8:30 мы играем в видеоигры.
Sekiz buçukta video oyunları oyunuyoruz.

12. После игр, мы готовим детей ко сну
Oyunmadan sonra, çocukları uyanmaya hazırlıyoruz.

13. Перед сном, мы читаем им сказку.
Uyunmadan önce, onlara bir masa okudum.

** Karikatür

Bu resimde iki durum görüyoruz. 

Bir çift ayakkabı indirim olmadan satıldığında bir hiç istiyor.

Bir indirim ile satıldığında herkes istiyor.

Bununla ilgili çok fazla sorun var:

- öncelikle, çoğu giysi üzerinde fiyat ve düşük kalite

- İkincisi, perakendeciler satışları artırmak için indirimler kullanıyor

- üçüncüsü, insanlar dolaplarını kötü planlıyor ve ihtiyaç duymadıkları şeyleri alıyorlar
  
** Yeni Hitit Ek Alıştırmalar 2, sayfa 4
*** 1
*Ben dün gece çok kötü bir rüya gördüm.*
Вчера ночью я видел очень плохой сон.
*Hemen yataktan kalktım ve mutfağa gittim.*
Немедленно встал с постели и пошёл на кухню.
*Mutfakta bir bardak su içtim.*
На кухне я выпил стакан воды.
*Televizyonu açtım.*
Включил телевизор.
*Televizyonda korku filmi vardı, bunun için televizyonu hemen kapattım.*
По телевизору шёл фильм ужасов, поэтому я его немедленно выключил.
*Beş on dakika müzik dinledim ve yatağıma gittim.*
Пятнадцать минут послушал музыку и пошёл в постель.
*Gözlerimi kapattım ve düşündüm.*
Закрыл глаза и подумал.
*Bu sırada evin kapısı calḋı*
В это время зазвучал дверной звонок.
*Ben kapıyı açmak istemedim, çünkü çok korktım*
Я не хотел открывать дверь, потому что очень боялся.
*Arkadaşıma telefon ettim ve ona "Lütfen benim yanıma gel!" dedim.*
Я позвонил своему другу и ему сказал "Приезжай пожалуйста ко мне".
*Kapı tekrar çaldı*
Звонок снова зазвучал.
*Ben yatak odasının kapasını kilitledim ve arkadaşımı bekledim.*
Я заперся в спальне и ждал своего друга.
*On beş dakika sonra arkadaşım cep telefonundan aradı ve "Ben geldim, lütfen kapıyı aç" dedi*
Через пятнадцать минут мой друг позвонил по сотовому и сказал "Я пришёл, пожалуйста открой дверь!"
*Ben hemen kapıyı açtım ve ona sarıldım.*
Я сразу открыл дверь и его обнял.
*Dün gece benim için çok kötü geçti, hiç uyumadım.*
Прошлая ночь для меня прошла очень плохо, вообще не спал.
*Bu sabah işe de gec geldim.*
Утром на работу не пошёл.

*** 2
1. Siz geçen yıl tatilde Antalya'ya gittiniz mi?
2. Dün sokakta kiminle karşılaştınız?
3. Ali ile Ayşe sınavdan kötü not aldı ve çok üzüldü.
4. Sen bu resimleri daha önce gördün mü?
5. Dün çok yağmur yağdı bu sebeple biz pikniğe gitmediz.
6. Sen niçin hiç yemek yemedin?
7. Ben bu filmi daha önce seyrettim.
8. Siz dün gazete okudunuz mu?
9. Dün okula geldim, ama ders yapmadım.
10. Maria, Elena'yla sınıfta sohbet etti.
11. Marina'yla Rita teneffüste hiç çay içmedi.
12. Babam daha Ankara'dan döndü
13. Öğretmen biraz önce bu kelimeyi tahtaya yazdı.
14. Dün okuldan saat kaçta çıktın?
15. O sana yalan söyledi
16. Pencereyi ben açmadım, Ayşe açtı.
17. Onunla yemekte hiç konuşmadım.
18. Bardak biraz önce yere düştu ve kırıldı.
19. Kızım bir saat önce yatağa yattı ama uyumadı.
20. Biz dün akşam ödev yapmadız, çunkü misafir geldiz.
21. Onalr partiye gitmedi, çünkü Ayşe onları partiye davet etmedi.
22. Sabah saat çaldı ve ben uyandım.
23. Öğretmen bu grameri geçen gün anlattı.
24. Ben dün size ödev verdi mi?
25. Siz hiç vapura binmediniz mi?
26. Ben dün akşam pilav pişirdim.
27. Biz geçen hafta sonu Izmir'e gittiniz mi? 
28. Ben bu filmi geçen hafta seyrettim.
29. Ben hiç İtalya'ya gitmedim.
30. Geçen gün çok yağmur yağdı.
31. Ben hiç uçağa binmedim. Sen bindin mi?
32. Merve Türkiye'ye döndü mü?    
33. Dün iki saat Türkçe çalıştım.
34. Ben bir yıl önce üniversiteyi bitirdim.

** Заметки
   https://www.turkishexplained.com/wordbanana.htm
   - lAnmAk — суффикс, означающий "стал". Hasta oldu, hastalandı. Zenginlendi.
   - lAşmAk — суффикс, означающий "стал", но другой. :)
   - (y)la — суффикс Vasita hali — творительного падежа.
** Вопросы
   ben ya da karım kahvaltı yapıyorum/yapıyor/yapıyoruz?
   Siz hiç vapura binmediniz mi?/Siz hiç vapura bindiniz mi?
